### PR TITLE
Optionally chain data from acknowledge

### PR DESCRIPTION
**Pull request by lukeingalls**

### CODE REVIEW

**Comment by lukeingalls** [comment]
I signed the cla during github downtime. Don't know if github action is supposed to be updated once I do

**Comment by nohe427** [comment]
@lukeingalls - Could you run prettier for us to make the bots happy.

It looks like we missed adding `data` proerty to that one `apiResponse` object. Have you manually tested the change to verify that it doesn't break anything?

**Comment by nohe427** [comment]
On an additional note, I reran the CLA bot and saw that you are approved. Thank you!

**Comment by lukeingalls** [comment]
I haven't manually run anything in this repo. I am reimplementing it in another and that is how I discovered the issue. My reimplemented version is definitely working now so this one should too.

**Review by joycetoh8 — APPROVED** [review]
Thanks for catching this, Luke!

**Pull request merged**
